name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]

    steps:
    # Bước 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Set executable permission for bash.sh
    - name: Set executable permission
      run: chmod +x ./bash.sh
      
    # Bước 2: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Bước 3: Run Bash script
    - name: Run Bash script
      run: ./bash.sh ${{ matrix.environment }}
