name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, staging, prod]

    steps:
    # Bước 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Bước 3: Set up Google Cloud credentials
    - name: Set up Google Cloud credentials
      run: echo "${{ secrets.GCP_CREDENTIALS }}" > $GITHUB_WORKSPACE/credentials.json
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json

    # Bước 4: Initialize Terraform with debug
    - name: Initialize Terraform with debug
      run: |
        export TF_LOG=DEBUG
        terraform init \
          -chdir=environments/${{ matrix.environment }} \
          -input=false \
          -no-color \
          -lock=false \
          -upgrade
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/credentials.json


    # Bước 5: Plan Terraform
    - name: Plan Terraform
      run: terraform -chdir=environments/${{ matrix.environment }} plan \
            -var-file=../../shared.tfvars \
            -input=false

    # Bước 6: Apply Terraform
    - name: Apply Terraform
      if: github.event_name == 'push'
      run: terraform -chdir=environments/${{ matrix.environment }} apply \
            -auto-approve \
            -var-file=../../shared.tfvars
